openapi: 3.1.0
x-stoplight:
  id: b02cv95ew8lae
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000/v1'
paths:
  /signup:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  idToken:
                    type: string
                    x-stoplight:
                      id: hzhbkn9x69v8y
                  refreshToken:
                    type: string
                    x-stoplight:
                      id: deny3s64fmo37
                  expiresIn:
                    type: integer
                    x-stoplight:
                      id: a054se8dlz3d5
                  email:
                    type: string
                    x-stoplight:
                      id: ybphe96ka87qn
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  x-stoplight:
                    id: f8fcdly6khk8c
                  format: password
              required:
                - email
                - password
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  password: password
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-internal: false
      tags:
        - ユーザー情報
    parameters: []
  /refresh_token:
    post:
      summary: ''
      operationId: post-refresh_token
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  refresh_token:
                    type: string
                    x-stoplight:
                      id: 6ukbh883wz142
                  idToken:
                    type: string
                    x-stoplight:
                      id: ppx3tzc45vb0d
                  expiresIn:
                    type: string
                    x-stoplight:
                      id: ts0iten2b9qjh
                required:
                  - refresh_token
                  - idToken
                  - expiresIn
      description: idTokenを取得
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  x-stoplight:
                    id: ah334hbyov5re
              required:
                - refresh_token
  /user/information:
    put:
      summary: put-user-information
      operationId: put-user-nformation
      responses:
        '201':
          description: Created
          headers:
            header-0:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  x-stoplight:
                    id: cw2t49irenl5q
                lastName:
                  type: string
                  x-stoplight:
                    id: za20xkad5c4f7
                firstNameKana:
                  type: string
                  x-stoplight:
                    id: 96qdj5qlzeq5x
                lastNameKana:
                  type: string
                  x-stoplight:
                    id: p1u2raaltorh3
                birthDate:
                  type: string
                  x-stoplight:
                    id: ilr0inhiq8638
                  format: date
                faculty:
                  $ref: '#/components/schemas/Faculty'
                  x-stoplight:
                    id: txdrhpy27los5
              required:
                - firstName
                - lastName
                - firstNameKana
                - lastNameKana
                - birthDate
                - faculty
      tags:
        - ユーザー情報
    parameters: []
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  idToken:
                    type: string
                    x-stoplight:
                      id: h0s73dqkl9el1
                  refreshToken:
                    type: string
                    x-stoplight:
                      id: d0oml226wnmu3
                  expiresIn:
                    type: integer
                    x-stoplight:
                      id: 08vla2qs7eklo
                  email:
                    type: string
                    x-stoplight:
                      id: lgrze4io69wh5
      tags:
        - ユーザー情報
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  x-stoplight:
                    id: ef99gbd2lic0t
                email:
                  type: string
                  x-stoplight:
                    id: 1mch8gn3zh9dr
                  format: email
        description: ''
      description: ''
  /user/reseachers:
    parameters: []
    post:
      summary: ''
      operationId: post-user-reseacher
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Researcher'
      requestBody:
        content: {}
        description: ''
  /user/reseacher/recruits:
    parameters: []
    post:
      summary: ''
      operationId: post-recuruit
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recuruit'
            application/xml:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Recuruit:
                  $ref: '#/components/schemas/Recuruit'
                  x-stoplight:
                    id: lx8iyrkfkriva
        description: ''
      x-extension-1: null
      description: ''
      tags:
        - 投稿
  /user/students:
    post:
      summary: ''
      operationId: post-user-student
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
      tags:
        - 学生
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                age:
                  type: integer
                  x-stoplight:
                    id: u8y2a2yqgnbrd
                sex:
                  type: integer
                  x-stoplight:
                    id: ahffh40v9kfqw
                grade:
                  type: integer
                  x-stoplight:
                    id: j4mu7y7n6z04f
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: ''
      description: ''
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      x-stoplight:
        id: a3lizesgzq612
      x-tags:
        - ユーザー情報
      properties:
        firstName:
          type: string
          x-stoplight:
            id: 0hsbrb9jnk58f
        lastName:
          type: string
          x-stoplight:
            id: 55ohxoz7jf6hq
        firstNameKana:
          type: string
          x-stoplight:
            id: 6ki6odd9qyznu
        lastNameKana:
          type: string
          x-stoplight:
            id: da432p935vq8t
        email:
          type: string
          format: email
          x-stoplight:
            id: 3u31r7advx0cl
        birthDate:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: 3nuzi525yxbom
        faculty_id:
          $ref: '#/components/schemas/Faculty'
          x-stoplight:
            id: jwyu1uyti3vlu
      required:
        - firstName
        - lastName
        - firstNameKana
        - lastNameKana
        - email
        - birthDate
        - faculty_id
    Faculty:
      title: Faculty
      x-stoplight:
        id: oxbfshzop8n8r
      type: object
      x-tags:
        - ユーザー情報
      properties:
        id:
          type: string
          x-stoplight:
            id: 2jj9xj8jb7yms
        name:
          type: string
          x-stoplight:
            id: x63kw1rjvz33c
        order:
          type: integer
          x-stoplight:
            id: na8lsiglmcm9u
    Student:
      title: Student
      x-stoplight:
        id: v1i0mbx5lk69j
      type: object
      properties:
        userId:
          $ref: '#/components/schemas/User'
          x-stoplight:
            id: exw0k0o47ijhz
        id:
          type: string
          x-stoplight:
            id: 2ymkwwbywho48
        grade:
          type: integer
          x-stoplight:
            id: qipdkp1g54o2l
        sex:
          type: integer
          x-stoplight:
            id: 9gfdcvv9d9xca
    Researcher:
      title: Researcher
      x-stoplight:
        id: lcwmq0pffgl5l
      type: object
      properties:
        userId:
          $ref: '#/components/schemas/User'
          x-stoplight:
            id: ohya27tvwme2j
    Recuruit:
      title: Recuruit
      x-stoplight:
        id: p0detnsz2y9h7
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: 4gcs9vyicvxho
        title:
          type: string
          x-stoplight:
            id: a0gv5s1fiaa3x
        description:
          type: string
          x-stoplight:
            id: 3yc2zwkw02q4f
        caution:
          type: string
          x-stoplight:
            id: 99yecyqco89c8
        restriction:
          type: string
          x-stoplight:
            id: z8ifc9ko1svcw
        rabo:
          type: string
          x-stoplight:
            id: 7hb180ah8asiy
        testing_field:
          type: string
          x-stoplight:
            id: bq306kv81fqwe
        experment_period:
          type: string
          x-stoplight:
            id: msfw2o6ilzx9a
        reward:
          type: string
          x-stoplight:
            id: el4wtr1fepxvi
        item:
          type: string
          x-stoplight:
            id: 47uusex1yj45p
        recruitment_dead_line:
          type: string
          x-stoplight:
            id: cnrascea2yrdh
          format: date
        Researcher:
          $ref: '#/components/schemas/Researcher'
          x-stoplight:
            id: d0rcr0a247lf8
